<?php

/**
 * Loading all ACF fields and options from this file
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5656136da36c1',
	'title' => 'Page Subtitle',
	'fields' => array (
		array (
			'key' => 'field_5656137207688',
			'label' => '',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => 'Subtitle',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-front-jumbtron.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-front-slider-premium.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_565614e5b6a4d',
	'title' => 'Alternative Slider Option',
	'fields' => array (
		array (
			'key' => 'field_5656151f21ae4',
			'label' => 'Use this Slider',
			'name' => 'use_this_slider',
			'type' => 'radio',
			'instructions' => 'If you prefer Revolution Slider or Layout Slider you can use them with this theme. Select which slider you want to use and fill in the <strong>ID only.</strong> Please note that both sliders are not included, you can buy Revolution Slider <a href="http://codecanyon.net/item/slider-revolution-responsive-wordpress-plugin/2751380?ref=QreativeThemes">here</a> and Layer Slider <a href="http://codecanyon.net/item/layerslider-responsive-wordpress-slider-plugin-/1362246?ref=QreativeThemes">here</a>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'rev' => 'Revolution Slider',
				'layer' => 'Layer Slider',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5656154721ae5',
			'label' => 'Revolution Slider',
			'name' => 'revolution_slider_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5656151f21ae4',
						'operator' => '==',
						'value' => 'rev',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5656155d21ae6',
			'label' => 'Layer Slider',
			'name' => 'layer_slider_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5656151f21ae4',
						'operator' => '==',
						'value' => 'layer',
					),
				),
				array (
					array (
						'field' => 'field_5656151f21ae4',
						'operator' => '==',
						'value' => 'layer',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-front-slider-premium.php',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56561139cbe1f',
	'title' => 'Page slider',
	'fields' => array (
		array (
			'key' => 'field_58a1e6d98c4c9',
			'label' => 'Slides',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56561180d769e',
			'label' => 'Image slides',
			'name' => 'slides',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_565611f5d769f',
					'label' => 'Image',
					'name' => 'slide_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'physio-qt-slider-l',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56561229d76a0',
					'label' => 'Top heading',
					'name' => 'slide_small_heading',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56561143d769d',
								'operator' => '==',
								'value' => 'use_captions',
							),
						),
					),
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_56561246d76a1',
					'label' => 'Heading',
					'name' => 'slide_heading',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56561143d769d',
								'operator' => '==',
								'value' => 'use_captions',
							),
						),
					),
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
				),
				array (
					'key' => 'field_5656126fd76a2',
					'label' => 'Content',
					'name' => 'slide_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56561143d769d',
								'operator' => '==',
								'value' => 'use_captions',
							),
						),
					),
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'text',
					'toolbar' => 'basic',
					'media_upload' => 0,
				),
				array (
					'key' => 'field_56717e88b42fb',
					'label' => 'Link slide',
					'name' => 'slide_link',
					'type' => 'text',
					'instructions' => '(Optional) Link the image to a URL',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56561143d769d',
								'operator' => '==',
								'value' => 'no_captions',
							),
						),
					),
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5671849ba861b',
					'label' => 'Target link',
					'name' => 'slide_link_target',
					'type' => 'radio',
					'instructions' => 'Open link in new browser window?',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56561143d769d',
								'operator' => '==',
								'value' => 'no_captions',
							),
						),
					),
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
		array (
			'key' => 'field_58a1e6ee8c4ca',
			'label' => 'Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5671882add8de',
			'label' => 'Slide animation',
			'name' => 'slide_animation',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'carousel-slide' => 'Slide',
				'carousel-fade' => 'Fade',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5656129fd76a3',
			'label' => 'Slider autocycle',
			'name' => 'slide_autocycle',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Automatically cycle the slider',
			'default_value' => 1,
		),
		array (
			'key' => 'field_565612ded76a4',
			'label' => 'Slide interval',
			'name' => 'slide_interval',
			'type' => 'number',
			'instructions' => 'Cycle interval (1s = 1000ms)',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5656129fd76a3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 8000,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'ms',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_56561143d769d',
			'label' => 'Captions on slides',
			'name' => 'slide_captions',
			'type' => 'radio',
			'instructions' => 'Enable captions for each slide',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'use_captions' => 'Use captions',
				'no_captions' => 'Don\'t use captions',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'use_captions',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_58ece3ee9b1d2',
			'label' => 'Caption alignment',
			'name' => 'slide_caption_alignment',
			'type' => 'radio',
			'instructions' => 'Align the caption on the slides',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56561143d769d',
						'operator' => '==',
						'value' => 'use_captions',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'left' => 'Left',
				'center' => 'Center',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'use_captions',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-front-jumbtron.php',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5655fd6b3b271',
	'title' => 'Header settings',
	'fields' => array (
		array (
			'key' => 'field_573f002b12837',
			'label' => 'Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_573eff8212835',
			'label' => 'Topbar',
			'name' => 'topbar',
			'type' => 'radio',
			'instructions' => 'Show or hide the topbar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5821cb1834a9e',
			'label' => 'Header widgets',
			'name' => 'widget_bar',
			'type' => 'radio',
			'instructions' => 'Show or hide the header widget bar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5821d82b57218',
			'label' => 'Page header',
			'name' => 'page_header',
			'type' => 'radio',
			'instructions' => 'Show or hide the page header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_573effb412836',
			'label' => 'Pages header alignment',
			'name' => 'header_text_align',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'left' => 'Left',
				'center' => 'Center',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'left',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_573f0176dc619',
			'label' => 'Page title',
			'name' => 'display_page_title',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_56a7a33f17e79',
			'label' => 'Page title color',
			'name' => 'page_title_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_573f01aadc61a',
			'label' => 'Subtitle color',
			'name' => 'subtitle_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_5821dbb10d926',
			'label' => 'Breadcrumbs',
			'name' => 'breadcrumbs',
			'type' => 'radio',
			'instructions' => 'Show or hide the breadcrumbs',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_573f003f12838',
			'label' => 'Background',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5655fda0b8697',
			'label' => 'Background image',
			'name' => 'header_bg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5655fe25b8698',
			'label' => 'Background image horizontal position',
			'name' => 'header_bg_horizontal',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'left' => 'Left',
				'center' => 'Center',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'left',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5655fe6bb8699',
			'label' => 'Background image vertical position',
			'name' => 'header_bg_vertical',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'top' => 'Top',
				'center' => 'Center',
				'bottom' => 'Bottom',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5655fe8bb869a',
			'label' => 'Background image size',
			'name' => 'header_bg_size',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'auto' => 'Auto',
				'cover' => 'Cover',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5655fea3b869b',
			'label' => 'Background image attachment',
			'name' => 'header_bg_attachment',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'scroll' => 'Scroll',
				'fixed' => 'Fixed',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5655fee3b869c',
			'label' => 'Background color',
			'name' => 'header_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-front-jumbtron.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-front-slider-premium.php',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5655eb257204f',
	'title' => 'Sidebar Settings',
	'fields' => array (
		array (
			'key' => 'field_5655eb4b31ecd',
			'label' => 'Display sidebar',
			'name' => 'sidebar',
			'type' => 'radio',
			'instructions' => 'Set the position of the sidebar on this page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'hide' => 'Hide',
				'left' => 'Left',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'right',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5655f6b4f706f',
			'label' => 'Pull sidebar',
			'name' => 'pull_sidebar',
			'type' => 'radio',
			'instructions' => 'Pull the sidebar to overlap the page heading',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5655eb4b31ecd',
						'operator' => '==',
						'value' => 'left',
					),
				),
				array (
					array (
						'field' => 'field_5655eb4b31ecd',
						'operator' => '==',
						'value' => 'right',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'no_pull' => 'Don\'t Pull Sidebar',
				'pull' => 'Pull Sidebar',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no_pull',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-front-jumbtron.php',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-front-slider-premium.php',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;